version: '3.8'

services:
  weave-ui:
    image: weave/ui:dev
    container_name: weave-ui-dev
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    restart: unless-stopped
    ports:
      - "3001:80"
    networks:
      - weave_network_dev
    volumes:
      - .:/code:rw

networks:
  weave_network_dev:
    name: weave_network_dev
    driver: bridge

    